name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup V
        run: |
          cd $HOME
          git clone https://github.com/vlang/v v && cd v
          make
          sudo ./v symlink
      - name: Code formatting
        run:  v fmt -verify .
      - name: Build
        run: v .

