name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
			- name: Setup V
      	uses: nocturlab/setup-vlang-action@v1
      	with:
        	v-version: latest
      	id: v
			- name: Code formatting
				run:  v fmt -verify .
			- name: Build
				run: v .

